("integer literals" 123 "123")
("negative integer literals" -4 "-4")
("true literal" #t "#t")
("false literal" #f "#f")
("char literal" #\1 "#\1")
("symbol literal" hello-world "hello-world")
("vector literal" #(1 2 3) "#(1 2 3)")
("string literal" "hello world" "\"hello world\"")
